name: build

on:
  # pull_request:
  #   branches:
  #   - main
  #   - develop
  # push:
  #   branches:
  #   - main
  #   - develop
  #   tags:
  #   - v*
  workflow_dispatch:

jobs:
  python-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install hatch
      uses: pypa/hatch@install
    - name: Build python package
      run: hatch build
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-distributions
        path: dist/
        if-no-files-found: error

  pypi-publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: python-build
    # TODO add environment and permissions
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: python-distributions
        path: dist/
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
