name: tests

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install hatch
      uses: pypa/hatch@install
    - name: Run linter and formatter checks
      run: hatch fmt --check
    - name: Run tests
      run: hatch test --all
